--DROP TABLE public.iot_device;
--CREATE TABLE public.iot_device (
--	device_id varchar NOT NULL,
--	device_status varchar NOT NULL,
--	device_temp varchar NOT NULL,
--	CONSTRAINT iot_device_pk PRIMARY KEY (device_id)
--);
--CREATE UNIQUE INDEX iot_device_device_id_idx ON public.iot_device USING btree (device_id);
--
--DROP TABLE public.sim;
--CREATE TABLE public.sim (
--	sim_id varchar NOT NULL,
--	operator_code varchar NOT NULL,
--	country_name varchar NOT NULL,
--	sim_status varchar NOT NULL,
--	device_id varchar NOT NULL,
--	CONSTRAINT sim_pk PRIMARY KEY (sim_id),
--	CONSTRAINT sim_fk FOREIGN KEY (device_id) REFERENCES public.iot_device(device_id)
--);
--CREATE UNIQUE INDEX sim_sim_id_idx ON public.sim USING btree (sim_id);