version: '3.7'
services:
    database-server:
        image: postgres:latest
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        networks:
            - spring-boot-network
    device-server:
        container_name: device-server
        build: .
        image: device-server:latest
        ports:
            - 8080:8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://database-server:5432/postgres
        networks:
            - spring-boot-network
        depends_on:
            - database-server
networks:
    spring-boot-network:
        driver: bridge