version: '3.7'
services: 
    database:
        image: postgres:latest
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        volumes: 
            - ./data/db:/var/lib/postgresql/data